# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managehost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='cpustat',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='iostat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='memory',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ms',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='rootdisk',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='uptime',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
